Netapp_VLAN:
  cluster1-01:
    cluster_node: cluster1-01
    vlan:
    - parent_interface: e0c
      vlanid: '100'
    - parent_interface: e0d
      vlanid: '100'
    - parent_interface: e0c
      vlanid: '400'
    - parent_interface: e0d
      vlanid: '400'
  cluster1-02:
    cluster_node: cluster1-02
    vlan:
    - parent_interface: e0c
      vlanid: '100'
    - parent_interface: e0d
      vlanid: '100'
    - parent_interface: e0c
      vlanid: '400'
    - parent_interface: e0d
      vlanid: '400'
Netapp_Broadcast_Domain:
  test-be-iscsi01:
    name: test-be-iscsi01
    mtu: '9000'
    ipspace: Default
    broadcast_ports:
    - cluster1-01:e0c-100
    - cluster1-01:e0d-100
    - cluster1-02:e0c-100
    - cluster1-02:e0d-100
  test-be-iscsi02:
    name: test-be-iscsi02
    mtu: '9000'
    ipspace: Default
    broadcast_ports:
    - cluster1-01:e0c-400
    - cluster1-01:e0d-400
    - cluster1-02:e0c-400
    - cluster1-02:e0d-400
Netapp_SVM:
  evx3300233:
    name: evx3300233
    root_vol: evx3300233_root
    root_vol_aggr: aggr1_cluster1_01
    root_vol_security_style: unix
    allowed_protocols: cifs
    comment: Test Platform - CIFS
Netapp_SVM_LIFs:
  evx3300233:
    vserver: evx3300233
    interface_name: evx3300233-mgmt-201
    service_policy: default-management
    role: data
    protocols:
    - none
    address: 192.168.0.14
    netmask: 255.255.255.0
    home_node: cluster1-01
    home_port: e0c
    failover_policy: system-defined
    failover_group: Default
    firewall_policy: mgmt
    is_auto_revert: 'yes'
Netapp_DNS:
  evx3300233:
    vserver: evx3300233
    domains:
    - demo.netapp.com
    nameservers:
    - 192.168.0.253
Netapp_Volumes:
  evx3300233_testvol:
    name: evx3300233_testvol
    aggregate_name: aggr1_cluster1_01
    vserver: evx3300233
    size: '5'
    volume_security_style: ntfs
    junction_path: "/evx3300233_testvol"
    export_policy: ''
    comment: CIFS Test volume
Netapp_CIFS_Server:
  evx3300233:
    name: evx3300233
    domain: demo.netapp.com
    vserver: evx3300233
    admin_user_name: Administrator
    admin_password: Netapp1!
    ou: CN=Computers
Netapp_CIFS_Shares:
  evx3300233_testvol:
    share_name: evx3300233_testvol
    path: "/evx3300233_testvol"
    vserver: evx3300233
    acls:
    - user_or_group: DEMO\Administrator
      permission: full_control
    - user_or_group: DEMO\testuser
      permission: read
